---
name: Publish version

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

env:
  artifact_path: pkg

jobs:
  artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: bundle exec rake build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          if-no-files-found: error
          path: ${{ env.artifact_path }}/
  release:
    name: GitHub Releases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: ${{ env.artifact_path }}/
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Generate release notes
        id: changelog
        run: |
          mkdir tmp
          outfile=tmp/changelog.txt
          echo "outfile=${outfile}" >> $GITHUB_OUTPUT
          npx standard-changelog@^2.0.0 --release-count 2 --infile $outfile.tmp
          sed '1,7d' $outfile.tmp > $outfile
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          body_path: ${{ github.workspace }}/${{ steps.changelog.outputs.outfile }}
          files: ${{ env.artifact_path }}/*
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, 'pre') }}
  rubygems:
    name: RubyGems.org
    uses: ./.github/workflows/publish-gem.yml
    needs: artifacts
    with:
       host: https://rubygems.org
       key: rubygems
       artifact_path: pkg
    secrets:
       token: ${{ secrets.RUBYGEMS_API_KEY }}
  github:
    name: GitHub Packages
    uses: ./.github/workflows/publish-gem.yml
    needs: artifacts
    with:
       host: https://rubygems.pkg.github.com/${{ github.repository_owner }}
       key: github
       artifact_path: pkg
    secrets:
       token: ${{ secrets.GITHUB_TOKEN }}
